CREATE TABLE IF NOT EXISTS counters (
  name TEXT PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS daily_counts (
  day TEXT PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);
